version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - SHOPIFY_API_KEY=${SHOPIFY_API_KEY}
      - SHOPIFY_PASSWORD=${SHOPIFY_PASSWORD}
      - SHOPIFY_STORE_NAME=${SHOPIFY_STORE_NAME}
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

